# Generated by Django 5.0.1 on 2024-01-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='tasks',
        ),
    ]
